name: Build and Release

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true
          
      - name: Get version
        id: get_version
        run: |
          # Check if this is a tag build
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Extract version from tag
            VERSION=${GITHUB_REF#refs/tags/}
          else
            # Use short SHA of current commit
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version: $VERSION"

      - name: Build for Linux AMD64
        run: |
          GOOS=linux GOARCH=amd64 go build -o builds/delivr-linux-amd64-${{ env.VERSION }} -v .
        
      - name: Upload Linux AMD64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: delivr-linux-amd64-${{ env.VERSION }}
          path: builds/delivr-linux-amd64-${{ env.VERSION }}
          retention-days: 90
          
      - name: List build directory content
        run: ls -la builds/
